# ==========================================================
# REGUAI - SEMANTIC SEARCH SERVICE
# ==========================================================

"""
Service responsible for semantic similarity search.

This service compares embeddings generated by the local
Sentence Transformer model and finds the document chunks
that are most semantically similar to a query.

Pipeline:

    User Query
        ↓
    Query Embedding
        ↓
    Compare With Chunk Embeddings
        ↓
    Similarity Scores
        ↓
    Top Matching Chunks
"""


from app.services.embedding_service import (
    generate_embedding
)


# ----------------------------------------------------------
# COSINE SIMILARITY
# ----------------------------------------------------------

def cosine_similarity(
    embedding_a: list[float],
    embedding_b: list[float]
) -> float:
    """
    Calculate cosine similarity between two embeddings.

    Cosine similarity ranges approximately from:

        -1 → completely opposite
         0 → unrelated
         1 → very similar

    Our embeddings are normalized, but normalization is
    handled here as well so this function remains safe.
    """

    if not embedding_a or not embedding_b:

        raise ValueError(
            "Embeddings cannot be empty."
        )


    if len(embedding_a) != len(embedding_b):

        raise ValueError(
            "Embeddings must have the same dimensions."
        )


    dot_product = sum(
        a * b
        for a, b in zip(
            embedding_a,
            embedding_b
        )
    )


    magnitude_a = sum(
        a * a
        for a in embedding_a
    ) ** 0.5


    magnitude_b = sum(
        b * b
        for b in embedding_b
    ) ** 0.5


    if magnitude_a == 0 or magnitude_b == 0:

        return 0.0


    return (
        dot_product
        / (magnitude_a * magnitude_b)
    )


# ----------------------------------------------------------
# SEARCH DOCUMENT CHUNKS
# ----------------------------------------------------------

def search_similar_chunks(
    query: str,
    embedded_chunks: list[dict],
    top_k: int = 3,
    minimum_score: float = 0.0
) -> list[dict]:
    """
    Find the most semantically similar document chunks
    for a given query.

    Parameters
    ----------
    query:
        Search query or compliance requirement.

    embedded_chunks:
        Document chunks containing embeddings.

    top_k:
        Maximum number of results to return.

    minimum_score:
        Minimum similarity score required for a result.

    Returns
    -------
    list[dict]
        Matching chunks sorted from highest similarity
        to lowest similarity.
    """

    if not query or not query.strip():

        raise ValueError(
            "Query cannot be empty."
        )


    if not embedded_chunks:

        return []


    if top_k <= 0:

        raise ValueError(
            "top_k must be greater than 0."
        )


    query_embedding = generate_embedding(
        query
    )


    results = []


    for chunk in embedded_chunks:

        chunk_embedding = chunk.get(
            "embedding"
        )


        if not chunk_embedding:

            continue


        similarity = cosine_similarity(
            query_embedding,
            chunk_embedding
        )


        if similarity >= minimum_score:

            result = {

                **chunk,

                "similarity_score": round(
                    similarity,
                    6
                )

            }


            results.append(
                result
            )


    results.sort(
        key=lambda item: item[
            "similarity_score"
        ],
        reverse=True
    )


    return results[:top_k]


# ----------------------------------------------------------
# SEARCH USING PRE-GENERATED QUERY EMBEDDING
# ----------------------------------------------------------

def search_with_embedding(
    query_embedding: list[float],
    embedded_chunks: list[dict],
    top_k: int = 3,
    minimum_score: float = 0.0
) -> list[dict]:
    """
    Search document chunks using an already-generated
    query embedding.

    This avoids generating the same query embedding again
    when multiple searches are performed.
    """

    if not query_embedding:

        raise ValueError(
            "Query embedding cannot be empty."
        )


    if not embedded_chunks:

        return []


    if top_k <= 0:

        raise ValueError(
            "top_k must be greater than 0."
        )


    results = []


    for chunk in embedded_chunks:

        chunk_embedding = chunk.get(
            "embedding"
        )


        if not chunk_embedding:

            continue


        similarity = cosine_similarity(
            query_embedding,
            chunk_embedding
        )


        if similarity >= minimum_score:

            results.append({

                **chunk,

                "similarity_score": round(
                    similarity,
                    6
                )

            })


    results.sort(
        key=lambda item: item[
            "similarity_score"
        ],
        reverse=True
    )


    return results[:top_k]


# ----------------------------------------------------------
# SEARCH DOCUMENT TEXT
# ----------------------------------------------------------

def search_document_text(
    query: str,
    text: str,
    chunk_size: int = 500,
    chunk_overlap: int = 100,
    top_k: int = 3,
    minimum_score: float = 0.0
) -> list[dict]:
    """
    Complete semantic-search pipeline.

    Takes raw document text, creates chunks, generates
    embeddings, and searches for the chunks most relevant
    to the query.

    Pipeline:

        Raw Text
           ↓
        Chunking
           ↓
        Embeddings
           ↓
        Semantic Search
           ↓
        Ranked Results
    """

    if not text or not text.strip():

        return []


    from app.services.embedding_service import (
        embed_document_text
    )


    embedded_chunks = embed_document_text(
        text=text,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )


    return search_similar_chunks(
        query=query,
        embedded_chunks=embedded_chunks,
        top_k=top_k,
        minimum_score=minimum_score
    )